[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,@executable_path/../Frameworks",
    "-C", "link-arg=-Wl,-rpath,@executable_path/../Resources/resources",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,@executable_path/../Frameworks",
    "-C", "link-arg=-Wl,-rpath,@executable_path/../Resources/resources",
]

[env]
# Set macOS deployment target to support older macOS versions
MACOSX_DEPLOYMENT_TARGET = "10.13"
